name: Latest blog post workflow
on:
  push:
    branches: [ master ]
  schedule:
    # Runs every hour
    - cron: '* * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEDIUM-POST-LIST
          feed_list: "https://medium.com/feed/@cloudopsgeek"
