name: Latest blog post workflow
on:
  push:
    branches: [ master ]
  schedule:
    # Runs every hour
    - cron: '0 * * * *'

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudopsgeek/cloudopsgeek@master
        with:
          comment_tag_name: MEDIUM-POST-LIST
          github_token: ${{ secrets.GITHUB_TOKEN }}
          feed_list: "https://medium.com/feed/@cloudopsgeek"
